### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by SaikumarRagala**

### CODE REVIEW

**Comment by duttakapil** [comment]
@SaikumarRagala can you add similar ideas for other Cloud Providers like Digital Ocean, GCP and others?

**Comment by SaikumarRagala** [comment]
@duttakapil , I can add for Azure, but for GCP and Digital ocean, It will be good, if someone from respective background can add it.

**Comment by duttakapil** [comment]
@SaikumarRagala yes, please add for Azure. We'll find someone for GCP and Digital Ocean from their teams

**Comment by duttakapil** [comment]
@SaikumarRagala I'll merge this PR for now. You can send another one for Azure later, and then we'll add ideas for GCP and Digital Ocean as well :D

**Pull request merged**
